Feature/category filters hookup
chingu-voyages/v42-geckos-team-20 pull request #64
Opened 2023-01-17 21:50 UTC by MattRueter

This will make buttons work. I also added a currency variable but no logic to update it yet.

2023-01-17 22:03 UTC, mailauki requested changes
The state for filteredProducts for "All" can be just setFilteredProducts(products), no need to map. And you can also useState(products) for the default rendering.

2023-01-17 22:53 UTC, mailauki commented
Send one prop <ProductCard product={product} /> in Catalog. Destructor prop within component const { id, name, seller, image } = product in ProductCard.

2023-01-20 23:02 UTC, MattRueter commented
I've made those changes.  Still could use some simplifying but I suspect we'll need to do that across the app soon so holding off for now if you don't mind merging.

2023-01-21 00:29 UTC, mailauki approved these changes

2023-01-21 00:29 UTC, merged